### PR TITLE
Update README.md

### LINKED ISSUE #6: Add contact info to README.md
Update the README.md file to add a **Questions?** section with the following info:

Twitter: [@CodeDotGov](https://twitter.com/CodeDotGov)
Email: code@gsa.gov
LinkedIn: [code-gov](https://www.linkedin.com/company/code-gov)
Join our #opensource-public Slack channel: https://chat.18f.gov/

### PR DESCRIPTION
**Pull request by jordanpapaleo**
Updated readme file to include a questions section

Fix #6

### CODE REVIEW

**Comment by saracope** [comment]
Can you go ahead an add the hyperlinks to Twitter and LinkedIn so those open to our account page? Thanks!

**Comment by jordanpapaleo** [comment]
Of course. Will you please give me the correct links so we know it’s done right. 

Sent from my smallest computer

> On Oct 4, 2019, at 2:22 PM, Sara Cope <notifications@github.com> wrote:
> 

﻿
Can you go ahead an add the hyperlinks to Twitter and LinkedIn so those open to our account page? Thanks!

**Comment by jordanpapaleo** [comment]
I pulled the links from the issue.  It should be good now.

**Comment by saracope** [comment]
Thanks!

**Pull request merged**
